### ISSUE TITLE
Simple Process Tracking: Edit Referral

### ISSUE THREAD

**Issue by petabite** [TritonSE/USHS-Housing-Portal#23]
# Overview

### API Stuffs

In  `frontend/src/api/referral.ts` create a `updateReferral` function that calls `PUT /api/referral/:id` appropriately.

### Functionality 

When any of dropdowns on a Referral row are modified, call `updateReferral` from above appropriately. Call `getUnitReferrals` to refresh the data in the Referrals table. The Last Updated time should be automatically updated (due to the Mongoose Timestamps feature used in the backend).

### Referral Routes

Implement the `PUT /api/referral/:id` route

## Acceptance Criteria
- [x] `PUT /api/referral/:id` route
- [x] `updateReferral` API route function
- [x] Dropdowns update the referrals correctly
