### ISSUE TITLE
Simple Process Tracking: Landlord Form Submission Review Flow

### ISSUE THREAD

**Issue by petabite** [TritonSE/USHS-Housing-Portal#24]
# Overview

## Frontend

Implement only the pending/approve banners and the Approve button on the Unit Specific Page - Housing Locator view ([Figma](https://www.figma.com/file/06vEDN5gtlHlC5hxNXMb4g/USHS-Designs?node-id=286%3A17098&mode=dev)).

### Unit API

In  `frontend/src/api/unit.ts` create a `approveUnit` function that takes in a Unit id as a parameter that calls `PUT /api/unit/:id/approve` appropriately.

### Functionality 

If the user is an HL, and the unit is not approved, show the Pending Approval banner at the top and the Approve Listing button at the bottom.

When the Approve Listing button at the bottom is clicked:
1. Call `approveUnit` appropriately.
2. Hide the Approve Listing button
3. Show the Approval Confirmed banner at the top

### Unit Approval Route

Implement the `PUT /api/unit/:id/approve` route ([reference](https://docs.google.com/document/d/19EBAxzbCyPdT6RgELrGsq6A2RPeDt2OSi5DYbFWm03k/edit#bookmark=id.vxe5bt27ec6q))
 
## Acceptance Criteria
- [ ] Unit Specific Page - Housing Locator view implementation
- [ ] `PUT /api/unit/:id/approve` route
- [ ] `approveUnit` API route function
- [ ] Working landlord form submission review flow

**Comment by petabite** [comment]
Frontend can be started after #44 merges
