### ISSUE TITLE
Simple Process Tracking: Unit Details - Case Manager View

### ISSUE THREAD

**Issue by petabite** [TritonSE/USHS-Housing-Portal#28]
# Overview

## Frontend

Implement the Unit Specific Details - Case Manager view ([Figma](https://www.figma.com/file/06vEDN5gtlHlC5hxNXMb4g/USHS-Designs?node-id=286%3A14653&mode=dev)) ignoring the Referrals table at the bottom. You may use dummy data for now until there are dummy test units in the database. Route this page to `/unit/:id` where `:id` is the id of the unit to be currently displayed on the page.

We will implement the Navigation bar and the Referrals section in a later task. 

### Unit API

In  `frontend/src/api/units.ts` create a `getUnit` function that takes in a Unit id as a parameter that calls `GET /api/units/:id` appropriately.

### Functionality

When the page loads, call `getUnit` with the `{id}` parameter from the URL path. Display the returned unit data appropriately on the page.

### Get Unit Route

Implement the `GET /api/units/:id` route

NOTE: You will need to wait for #18 before dummy test units can be created in the database since they are working on the POST /api/units route.

## Acceptance Criteria
- [x] Unit Specific Details - Case Manager view
- [x] `getUnit` API route function
- [x] `GET /api/units/:id` route
- [x] Page displays the correct unit (by `{id}` parameter in URL)
