### ISSUE TITLE
Simple Process Tracking: Add Referral

### ISSUE THREAD

**Issue by petabite** [TritonSE/USHS-Housing-Portal#29]
# Overview

## Frontend

Implement Add Referral popup flow ([Figma](https://www.figma.com/file/06vEDN5gtlHlC5hxNXMb4g/USHS-Designs?node-id=558%3A1168&mode=dev)).

### API Stuffs

In  `frontend/src/api/referrals.ts` create a `createReferral` function that calls `POST /api/referral` appropriately.

### Functionality

When "Add Referral" is clicked, show the "Add Referral" popup. You can get a list of existing renter candidates by calling `getRenterCandidates` (implemented in #35).

When the "Add Referral" button on the popup is clicked, do:
1. If "Add a new renter candidate" fields are filled out: call `createRenterCandidate` (implemented in #35) appropriately (saving the id of the new renter candidate for the next step).
2. Call `createReferral` appropriately to create the referral.
4. Call `getUnitReferrals` (implemented in #36) to refresh the data in the Referrals table
3. Hide the popup

### Referral Routes

Implement the `POST /api/referrals` route ([reference](https://docs.google.com/document/d/19EBAxzbCyPdT6RgELrGsq6A2RPeDt2OSi5DYbFWm03k/edit#bookmark=id.vz5kbbwgphhq)).

## Acceptance Criteria

- [x] `POST /api/referrals` route
- [x] `createReferral` API route function
- [x] End-to-end referral creation flow works
