### ISSUE TITLE
Simple Process Tracking: Change Unit Availability (HL)

### ISSUE THREAD

**Issue by petabite** [TritonSE/USHS-Housing-Portal#30]
# Overview

## Frontend
Implement the Change availability popup ([Figma](https://www.figma.com/file/06vEDN5gtlHlC5hxNXMb4g/USHS-Designs?node-id=615%3A6789&mode=dev)) including the "Change Availability" button.

### Unit API
In `frontend/src/api/units.ts` create an `updateUnit` function that calls `PUT /api/units/:id` appropriately. You will only need to update the `dateAvailable` or `leasedStatus` fields on Unit.

### Update Unit Route

Implement the `PUT /api/units/:id` route ([reference](https://docs.google.com/document/d/19EBAxzbCyPdT6RgELrGsq6A2RPeDt2OSi5DYbFWm03k/edit#bookmark=id.vxe5bt27ec6q))

## Acceptance Criteria
- [x] Working change availability popup flow
- [x] `updateUnit` API function
- [x] `PUT /api/units/:id` route
