### ISSUE TITLE
Simple Process Tracking: Renter Candidates

### ISSUE THREAD

**Issue by petabite** [TritonSE/USHS-Housing-Portal#35]
# Overview

### Renter Candidates API

Create a `getRenterCandidates` function in `frontend/src/api/renter-candidates.ts` that calls `GET /api/renter-candidates` and create a `createRenterCandidate` function that calls `POST /api/renter-candidates` appropriately.

### Renter Candidate Model

Implement the Renter Candidate model ([schema](https://docs.google.com/document/d/1ef1bwMTZANkUs5uyz-D93v85jv7CfmoDGwE5ANlX_BE/edit#bookmark=id.77oihdu4yyj0)).

### Renter Candidate Routes

Implement the `POST /api/renter-candidates` and `GET /api/renter-candidates` route ([reference](https://docs.google.com/document/d/19EBAxzbCyPdT6RgELrGsq6A2RPeDt2OSi5DYbFWm03k/edit#bookmark=id.dho87e3k6jj4))

## Acceptance Criteria
- [x] Renter Candidate Model
- [x] `POST /api/renter-candidates` route
- [x] `GET /api/renter-candidates` route
- [x] `createRenterCandidate` API route function
- [x] `getRenterCandidates` API route function
